---
  apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: dashmachine-data
  spec:
    resources:
      requests:
        storage: 10Gi
    accessModes:
      - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashmachine-server
  labels:
    app.kubernetes.io/name: dashmachine-server   
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dashmachine-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dashmachine-server
    spec:
      serviceAccountName: dashmachine-server
      containers:
      - name: dashmachine-server
        image: rmountjoy/dashmachine:latest
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name         
        volumeMounts:
            - mountPath: /dashmachine/dashmachine/user_data
              name: dashmachine-data  
      volumes:
        - name: dashmachine-data
          persistentVolumeClaim:
            claimName: dashmachine-data                          
      #Currently the only images are amd64 if you change the image change the node selector. 
      nodeSelector:
        kubernetes.io/arch: amd64  
---
kind: Service
apiVersion: v1
metadata:
  name: dashmachine
spec:
  ports:
    - name: http
      port: 5000
  selector:
    app.kubernetes.io/name: dashmachine-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashmachine-server